version: "3.3"
services:
  
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    privileged: true
    ports: 
      - "80:80"
      - "443:443"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - TZ=Asia/Shanghai
      - MY_ENV=product
      - CONTAINER_HOST_IP=47.97.182.56
    networks:
      - normal
    volumes: 
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/logs:/var/log/nginx
      - ./data/nginx/conf/conf.d:/etc/nginx/conf.d
      - /www:/www

  php:
    build: ./data/dockerfile/php
    container_name: php
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - MY_ENV=product
      - CONTAINER_HOST_IP=47.97.182.56
    networks:
      - normal
    volumes:
      - /www:/www
      - ./data/php/log:/var/log/php-fpm
      - ./data/php/conf.d/php.ini:/usr/local/etc/php/php.ini
      - ./data/php/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
networks:
  normal: